//! Parity witness for `(cond (() (quote wrong)) (t (quote right)))`
//! (`asm/entry-cond.s`) -- the bounded Nil/True `cond`-branching
//! fixture from `conformance.my`'s `compiler-corpus` tag
//! (`docs/compiler-oracle-corpus-parity-2026-09-11.md`, row 7),
//! wsm-my-lisp#4's last remaining `pending` row.
//!
//! Generated by cml's real front end -- `parser::parse` ->
//! `lower::lower_program` -> `X86FreestandingBackend::compile_program`
//! on the literal source string, NOT a hand-built `Ir::Cond`/`Ir::Quote`
//! node -- via `cml`'s `examples/emit_cond_witness.rs` (commit
//! `01ee4ae`), reproducible by re-running that example against any
//! future `cml` commit. `cml`'s own
//! `standalone_cond_true_false_branch_selection_witness` test already
//! asserts this compiles, links, and runs correctly in isolation; this
//! harness re-proves it here, linked against THIS repo's own
//! `asm/nucleus.s` (the entry itself calls no `wsm_*` primitive -- pure
//! branching and comparison against literal encoded words -- so linking
//! against the nucleus only satisfies the shared build, same as
//! `harness-lambda`'s identity fixture).
//!
//! SCOPE NOTE (do not conflate with a larger claim): this proves the
//! standalone fixture expression compiles and executes correctly. It
//! does NOT prove that `external/my-lisp/lib/meta-eval.my`'s own
//! `my-eval-cond` FUNCTION (part of the self-hosted evaluator's real
//! call graph, `docs/ROADMAP.md` Stage 2) compiles -- that still needs
//! general first-class application support in `x86_freestanding`,
//! tracked separately with `cml`, unresolved.
//!
//! Image-local symbol ids are cml's own alphabetical-interning choice
//! (`right` sorts before `wrong`, so `right`=1, `wrong`=2) -- not
//! hardcoded here as a coincidence, decoded the same way
//! `harness-cons`'s `render_symbol` decodes its own pinned fixture's
//! local ids.

use wsm_os_target::decode_symbol;

core::arch::global_asm!(include_str!("../../asm/nucleus.s"), options(att_syntax));
core::arch::global_asm!(include_str!("../../asm/entry-cond.s"), options(att_syntax));

unsafe extern "C" {
    fn wsm_entry(context: *mut core::ffi::c_void) -> u64;
}

fn render_symbol(word: u64) -> String {
    match decode_symbol(word) {
        Some(1) => "right".to_string(),
        Some(2) => "wrong".to_string(),
        Some(other) => format!("<symbol {other}>"),
        None => format!("<non-symbol word {word}>"),
    }
}

fn main() {
    let result = unsafe { wsm_entry(core::ptr::null_mut()) };
    let symbol = render_symbol(result);
    assert_eq!(symbol, "right", "result must match oracle: right");
    println!("cond: (cond (() (quote wrong)) (t (quote right))) -> {symbol}");
}
