//! Parity witness for bounded self-tail-recursion:
//! `(def countdown (lambda (n) (cond ((eq n 0) (quote done)) (t (countdown (- n 1)))))) (countdown N)`
//!
//! Generated by CML x86_freestanding backend (CML commit ae88fd23447c0d90d9d4c51e854fbb03218a95ae).
//! Linked EXCLUSIVELY against `asm/nucleus.s` (hand-written GNU asm for wsm_cons/car/cdr/eq/atom/fail)
//! without ANY Rust runtime primitive implementation linked.
//!
//! Proves:
//! 1. Tail-call jump (.Ltcloop_0) instead of recursive call
//! 2. Constant native stack frame ($112, %rsp) across 100,000 iterations
//! 3. Observable result matches my-lisp semantic oracle: `done`

core::arch::global_asm!(include_str!("../../asm/nucleus.s"), options(att_syntax));
core::arch::global_asm!(include_str!("../../asm/entry-countdown-100k.s"), options(att_syntax));

unsafe extern "C" {
    fn wsm_entry(context: *mut core::ffi::c_void) -> u64;
}

fn render_symbol(word: u64) -> String {
    // Tag::Symbol = 4; CML assigns: done=1 (word 12 = (1<<3)|4).
    match word >> 3 {
        1 => "done".to_string(),
        other => format!("<symbol {other}>"),
    }
}

fn main() {
    let ctx = core::ptr::null_mut();
    // Execute countdown from 100,000 to 0 on a single stack frame.
    let result = unsafe { wsm_entry(ctx) };
    assert_eq!(result & 0b111, 4, "result must be a Tag::Symbol word (tag 4)");
    let symbol = render_symbol(result);
    assert_eq!(symbol, "done", "result must match oracle: done");
    println!("countdown 100000 -> {}", symbol);
}
