#!/usr/bin/env bash
# Vertical slice witness: Lisp source -> CML x86-asm -> GNU as -> GNU ld
# -> native ELF -> execution, parity-checked against the my-lisp oracle.
#
# Production path (owner directive 2026-09-13): Lisp + x86-64 assembler only.
# No C and no Rust enter the executable: the assembly is GENERATED by CML from
# the Lisp fixture, then as(1)/ld(1) from GNU binutils turn it + asm/nucleus.s
# + the crt0-equivalent witness-bootstrap.s into a standalone ELF.
#
# Evidence printed:
#   the raw 64-bit result word (little-endian) and the oracle rendering,
#   plus a PASS/FAIL parity verdict.
set -uo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
FIXTURE="fixtures/atom-test/source.lisp"
CML_BIN="${CML_BIN:-$(command -v cml || echo /home/agents/GitHub/cml/target/release/cml)}"
DEST="/tmp/wsm-my-lisp-slice"
EXPECTED="fffffffffffffffc"

cd "$REPO_ROOT"
[ -f "$FIXTURE" ] || { echo "FIXTURE MISSING: $FIXTURE"; exit 1; }
[ -x "$CML_BIN" ] || { echo "CML NOT FOUND: $CML_BIN (set CML_BIN)"; exit 1; }
command -v as >/dev/null || { echo "as not found"; exit 1; }
command -v ld >/dev/null || { echo "ld not found"; exit 1; }

rm -rf "$DEST" && mkdir -p "$DEST"

echo "=== 1. Lisp source ==="
cat "$FIXTURE"

echo "=== 2. CML generates x86-64 assembler ==="
"$CML_BIN" x86-asm "$FIXTURE" > "$DEST/entry.s" || { echo "CML x86-asm failed"; exit 1; }
cat "$DEST/entry.s"

echo "=== 2b. generator path vs committed asm/entry-atom.s ==="
if diff "$DEST/entry.s" asm/entry-atom.s >/dev/null 2>&1; then
    echo "byte-identical: committed entry is CML-generated"
else
    echo "DIFFERS from asm/entry-atom.s (recheck provenance)" 1>&2
    exit 1
fi

echo "=== 3. GNU as: assemble entry + nucleus + bootstrap ==="
as -o "$DEST/entry.o"     "$DEST/entry.s"               || exit 1
as -o "$DEST/nucleus.o"   asm/nucleus.s                 || exit 1
as -o "$DEST/bootstrap.o" asm/witness-bootstrap.s        || exit 1

echo "=== 4. GNU ld: link standalone ELF ==="
ld -o "$DEST/slice" "$DEST/bootstrap.o" "$DEST/entry.o" "$DEST/nucleus.o" \
    || { echo "ld failed"; exit 1; }

echo "=== 5. native execution ==="
native="$("$DEST/slice" | od -An -tx8 | tr -d ' ')"
echo "native 64-bit word: $native"
echo "expected            $EXPECTED"

echo "=== 6. my-lisp oracle on same source ==="
oracle="$(printf '(atom (quote ()))\n' | my-lisp 2>&1 | grep '^t$\|^()$')"
echo "oracle rendering:   $oracle"

if [ "$native" = "$EXPECTED" ] && [ "$oracle" = "t" ]; then
    echo "PASS: native word = canonical t, oracle agrees"
    exit 0
else
    echo "FAIL parity" 1>&2
    exit 1
fi